[package]
name = "jsd"
version = "0.1.0"
authors = ["jarryliu <jarrysix@gmail.com>"]


[dependencies]
rand = "~0.4.0"
clap = "~2.32"
iron = "~0.6"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
