[package]
name = "jsa"
version = "0.1.0"
edition = "2018"
authors = ["jarryliu <jarrysix@gmail.com>"]


[dependencies]
clap = "~2.32"
iron = "~0.6"
serde = "~1.0"
serde_json = "~1.0"
serde_derive = "~1.0"
